name: Build Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -o type=local,dest=. --target artifacts .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rife_transition.so-${{ github.sha }}
          path: ./rife_transition.so
          if-no-files-found: error
